from fastapi import APIRouter, Depends, HTTPException, status
from json_db import JSONDatabase
from typing import List
import json
import os
import models
import schemas
from database import get_db
from auth import get_current_active_user, require_role

router = APIRouter(prefix="/api/curriculum", tags=["curriculum"])

# Fix: Look for curriculum in either backend/data or root data
SUBJECTS_FILE = os.path.join("data", "collegesubjects", "subjects.json")
if not os.path.exists(SUBJECTS_FILE):
    # Try looking one level up if we are in backend/
    PARENT_SUBJECTS_FILE = os.path.join("..", "data", "collegesubjects", "subjects.json")
    if os.path.exists(PARENT_SUBJECTS_FILE):
        SUBJECTS_FILE = PARENT_SUBJECTS_FILE

def get_subject_theme(name: str):
    """Helper to return consistent professional themes based on subject name keywords"""
    name = name.lower()
    if any(k in name for k in ["programming", "java", "python", "c", "web", "data"]):
        return {"primary": "#3b82f6", "accent": "#60a5fa", "gradient": "linear-gradient(135deg, #1d4ed8 0%, #3b82f6 100%)"}
    if any(k in name for k in ["math", "discrete", "algebra"]):
        return {"primary": "#8b5cf6", "accent": "#a78bfa", "gradient": "linear-gradient(135deg, #6c63ff 0%, #8b5cf6 100%)"}
    if any(k in name for k in ["physics", "chemistry", "electronics", "circuit"]):
        return {"primary": "#06b6d4", "accent": "#22d3ee", "gradient": "linear-gradient(135deg, #0891b2 0%, #06b6d4 100%)"}
    if any(k in name for k in ["networks", "security", "cryptography"]):
        return {"primary": "#10b981", "accent": "#34d399", "gradient": "linear-gradient(135deg, #059669 0%, #10b981 100%)"}
    if any(k in name for k in ["software", "design", "testing", "management"]):
        return {"primary": "#f59e0b", "accent": "#fbbf24", "gradient": "linear-gradient(135deg, #d97706 0%, #f59e0b 100%)"}
    if any(k in name for k in ["distributed", "operating", "architecture"]):
        return {"primary": "#f43f5e", "accent": "#fb7185", "gradient": "linear-gradient(135deg, #e11d48 0%, #f43f5e 100%)"}
    
    # Default theme
    return {"primary": "#6366f1", "accent": "#818cf8", "gradient": "linear-gradient(135deg, #4f46e5 0%, #6366f1 100%)"}

BRANCH_MAPPING = {
    "First Year": 0,
    "CSE": 1,
    "ECE": 2,
    "EEE": 3,
    "IT": 4,
    "MECH": 5,
    "AIML": 6,
    "AIDS": 7
}

def generate_subject_id(branch: str, semester: int, index: int) -> int:
    branch_idx = BRANCH_MAPPING.get(branch, 0)
    return (branch_idx * 10000) + (semester * 100) + index

def resolve_subject_by_id(subject_id: int):
    """Universal resolver for subject IDs generated by generate_subject_id"""
    if not os.path.exists(SUBJECTS_FILE):
        return None
        
    with open(SUBJECTS_FILE, "r") as f:
        data = json.load(f)
        
    branch_idx = subject_id // 10000
    semester = (subject_id % 10000) // 100
    index = subject_id % 100
    
    branch_name = next((k for k, v in BRANCH_MAPPING.items() if v == branch_idx), "First Year")
    
    try:
        if branch_name == "First Year":
            subjects = data.get("first_year", {}).get("subjects", [])
        else:
            subjects = data.get("branches", {}).get(branch_name, {}).get("semesters", {}).get(f"sem{semester}", {}).get("subjects", [])
            
        if 0 <= index < len(subjects):
            sub = subjects[index]
            sub_name = sub.get("name") if isinstance(sub, dict) else sub
            return {
                "id": subject_id,
                "name": sub_name,
                "code": sub.get("code", f"CORE-{branch_name}-{semester}-{index+1}") if isinstance(sub, dict) else f"CORE-{branch_name}-{semester}-{index+1}",
                "semester_id": semester,
                "theme_config": get_subject_theme(sub_name)
            }
    except Exception:
        pass
    return None

@router.get("/my-curriculum")
def get_my_curriculum(current_user: models.User = Depends(get_current_active_user)):
    """Get the specific curriculum for the logged-in student's branch and semester"""
    if current_user.role != "student":
        raise HTTPException(status_code=400, detail="Only students can access their curriculum")

    if not os.path.exists(SUBJECTS_FILE):
        return {"subjects": [], "message": "College subject database not found"}

    with open(SUBJECTS_FILE, "r") as f:
        data = json.load(f)

    # 1st year students (sem 1 or 2) use universal first_year subjects
    is_first_year = current_user.semester in (1, 2) if current_user.semester else False

    if is_first_year and "first_year" in data:
        raw_subjects = data["first_year"].get("subjects", [])
    else:
        if not current_user.branch or not current_user.semester:
            return {"subjects": [], "message": "Branch or semester not set for user"}
        
        branch_data = data["branches"].get(current_user.branch)
        if not branch_data:
            return {"subjects": [], "message": f"Curriculum for branch {current_user.branch} not found"}

        sem_key = f"sem{current_user.semester}"
        sem_data = branch_data["semesters"].get(sem_key)
        if not sem_data:
            return {"subjects": [], "message": f"Curriculum for {sem_key} not found"}
        raw_subjects = sem_data["subjects"]

    # Format into objects for frontend compatibility
    subjects = []
    for i, sub in enumerate(raw_subjects):
        if isinstance(sub, dict):
            sub_name = sub.get("name", "")
            course_outcomes = sub.get("course_outcomes", [])
            variants = sub.get("variants", [])
        else:
            sub_name = sub
            course_outcomes = []
            variants = []
        
        entry = {
            "id": generate_subject_id("First Year" if is_first_year else current_user.branch, current_user.semester, i),
            "name": sub_name,
            "code": sub.get("code", f"CORE-{current_user.semester}-{i+1}") if isinstance(sub, dict) else f"CORE-{current_user.semester}-{i+1}",
            "semester_id": current_user.semester,
            "theme_config": get_subject_theme(sub_name)
        }
        
        if course_outcomes:
            entry["course_outcomes"] = course_outcomes
        if variants:
            entry["variants"] = variants
        
        # Pass category and note fields
        if isinstance(sub, dict):
            if "category" in sub:
                entry["category"] = sub["category"]
            if "note" in sub:
                entry["note"] = sub["note"]
        
        subjects.append(entry)


    return subjects

@router.get("/years", response_model=List[schemas.Year])
def get_all_years(
    current_user: models.User = Depends(get_current_active_user),
    db: JSONDatabase = Depends(get_db)
):
    """Get all curriculum years with semesters and subjects"""
    years = db.read("curriculum_years")
    semesters = db.read("semesters")
    subjects = db.read("subjects")
    
    # Manual assembly for nested schemas
    result = []
    for y in years:
        y_semesters = []
        for s in [sem for sem in semesters if sem["year_id"] == y["id"]]:
            s_subjects = [sub for sub in subjects if sub["semester_id"] == s["id"]]
            s_copy = s.copy()
            s_copy["subjects"] = s_subjects
            y_semesters.append(s_copy)
        
        y_copy = y.copy()
        y_copy["semesters"] = y_semesters
        result.append(y_copy)
        
    return result

@router.get("/semesters/{semester_id}/subjects", response_model=List[schemas.Subject])
def get_semester_subjects(
    semester_id: int,
    current_user: models.User = Depends(get_current_active_user),
    db: JSONDatabase = Depends(get_db)
):
    """Get all subjects in a semester"""
    semester = db.get_by_id("semesters", semester_id)
    if not semester:
        raise HTTPException(status_code=404, detail="Semester not found")
    
    subjects = db.read("subjects")
    return [s for s in subjects if s["semester_id"] == semester_id]

@router.post("/subjects", response_model=schemas.Subject)
def create_subject(
    subject: schemas.SubjectCreate,
    current_user: models.User = Depends(require_role(["admin"])),
    db: JSONDatabase = Depends(get_db)
):
    """Create a new subject (admin only)"""
    # Check if code already exists
    subjects = db.read("subjects")
    if any(s["code"] == subject.code for s in subjects):
        raise HTTPException(status_code=400, detail="Subject code already exists")
    
    # Check if semester exists
    semester = db.get_by_id("semesters", subject.semester_id)
    if not semester:
        raise HTTPException(status_code=404, detail="Semester not found")
    
    return db.add("subjects", subject.dict())

@router.put("/subjects/{subject_id}", response_model=schemas.Subject)
def update_subject(
    subject_id: int,
    subject: schemas.SubjectBase,
    current_user: models.User = Depends(require_role(["admin"])),
    db: JSONDatabase = Depends(get_db)
):
    """Update a subject (admin only)"""
    item = db.get_by_id("subjects", subject_id)
    if not item:
        raise HTTPException(status_code=404, detail="Subject not found")
    
    updates = {"name": subject.name, "code": subject.code}
    return db.update("subjects", subject_id, updates)

@router.delete("/subjects/{subject_id}")
def delete_subject(
    subject_id: int,
    current_user: models.User = Depends(require_role(["admin"])),
    db: JSONDatabase = Depends(get_db)
):
    """Delete a subject (admin only)"""
    if not db.delete("subjects", subject_id):
        raise HTTPException(status_code=404, detail="Subject not found")
    return {"message": "Subject deleted successfully"}

@router.get("/subjects")
def get_subjects(branch: str, semester: int):
    """Get subjects for a specific branch and semester (used by dashboards)"""
    if not os.path.exists(SUBJECTS_FILE):
        return []

    with open(SUBJECTS_FILE, "r") as f:
        data = json.load(f)

    is_first_year = (branch == "First Year" or branch == "FY" or branch == "ALL")
    
    if is_first_year:
        raw_subjects = data.get("first_year", {}).get("subjects", [])
    else:
        branch_data = data.get("branches", {}).get(branch)
        if not branch_data:
            return []
        
        sem_key = f"sem{semester}"
        sem_data = branch_data.get("semesters", {}).get(sem_key)
        if not sem_data:
            return []
        raw_subjects = sem_data.get("subjects", [])

    # Format into objects with deterministic IDs
    subjects = []
    for i, sub in enumerate(raw_subjects):
        sub_name = sub.get("name") if isinstance(sub, dict) else sub
        entry = {
            "id": generate_subject_id("First Year" if is_first_year else branch, semester, i),
            "name": sub_name,
            "code": sub.get("code", f"CORE-{semester}-{i+1}") if isinstance(sub, dict) else f"CORE-{semester}-{i+1}",
            "semester_id": semester,
            "theme_config": get_subject_theme(sub_name)
        }
        
        if isinstance(sub, dict):
            entry.update({k: v for k, v in sub.items() if k not in entry})
            
        subjects.append(entry)

    return subjects
